filename: Environmental Emergencies v1.01 [FW] (1994)(Ken Anderson) [Educational, Trivia].zip
tdc_id: '13427.0'
title:
  screen: Environmental Emergencies
publisher: Ken Anderson
year: '1994'
genre:
- Educational
- Trivia
language: English
date:
  added: '2019-01-21T18:07:56'
  last_modified: '2019-01-21T18:07:56'
version: '1.01'
type: zip
tags:
- Freeware
media: Download
files:
- name: ENVIRON.COM
  size: 1010
  date: '1994-10-30T20:48:04'
  crc: '0x67eef34f'
- name: ENVIRON.ICO
  size: 766
  date: '1994-10-30T20:42:06'
  crc: '0x9aee368a'
- name: ENVIRON.TMT
  size: 30011
  date: '1994-11-10T22:26:18'
  crc: '0x37828322'
- name: FILES
  size: 1158
  date: '1994-11-10T22:35:12'
  crc: '0xb91000a3'
- name: FILE_ID.DIZ
  size: 348
  date: '1994-11-10T22:28:00'
  crc: '0xd724f6c4'
- name: GO.BAT
  size: 604
  date: '1994-11-10T22:28:16'
  crc: '0xcc770caf'
- name: HISTORY
  size: 1359
  date: '1994-11-10T22:30:10'
  crc: '0x40e4e853'
- name: README.TXT
  size: 780
  date: '1994-11-10T22:29:00'
  crc: '0x9b57b317'
- name: RUN.EXE
  size: 59200
  date: '1994-09-03T15:59:56'
  crc: '0x898e79b1'
- name: SUPPORT
  size: 1116
  date: '1994-11-10T22:30:32'
  crc: '0x4b29c750'
