filename: A-10 Tank Killer Config Patch (1996)(Sierra On-Line, Inc.) [Simulation, Addon].zip
tdc_id: '7649.7'
title:
  screen: A-10 Tank Killer Config Patch
publisher: Sierra On-Line, Inc.
year: '1996'
genre:
- Simulation
- Addon
language: English
date:
  added: '2022-07-09T11:03:16'
  last_modified: '2022-07-09T11:03:16'
type: zip
patch: true
files:
- name: CONFIG.EXE
  size: 6400
  date: '1992-01-24T12:00:00'
  crc: '0xc25cfe40'
- name: README.BAT
  size: 17
  date: '1996-01-16T11:17:50'
  crc: '0x5ca939bc'
- name: README.TXT
  size: 6088
  date: '1996-01-16T11:17:16'
  crc: '0x842aa850'
